#!/bin/sh

set -e

USER_SHELL=fish

# Install packages
if which yay > /dev/null; then
	PACKAGES=(
		# Terminal
		alacritty
		tmux

		# Shell
		fish
		starship

		# Font
		nerd-fonts-dejavu-complete

		# Vim
		deno

		# Sway - make unfocused more transparent
		python-i3ipc

		flavours
	)

	yay -S --noconfirm --needed "${PACKAGES[@]}"
fi

# Install themes
flavours update all &
flavours apply "$(cat ~/.local/share/flavours/lastscheme)"

# Set shell
USER_SHELL="$(chsh -l | grep "$USER_SHELL" | head -1)"
if [ "$SHELL" != "$USER_SHELL" -a -n "$USER_SHELL" ]; then
	chsh -s "$USER_SHELL"
fi

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --init

# Install tmux plugins
# TODO Use a makefile for this?
.tmux/plugins/tpm/bin/install_plugins

# Update fish plugins
fish -c "fisher update"
