# Starship configuration options:
# https://starship.rs/config

# Keep the prompt on one line
[line_break]
disabled = true

[status]
disabled = false
pipestatus = true

[time]
disabled = false

[cmd_duration]
min_time = 1000
